# PostgreSQL Development Setup
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tournament_postgres
    restart: always
    environment:
      POSTGRES_DB: tournament_db
      POSTGRES_USER: tournament_user
      POSTGRES_PASSWORD: tournament_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
